<?php
include_once "../mysql.php";


$cookie = $_COOKIE['name'];
$sql = "select * from selection where Sname='$cookie'";


echo <<<Eof
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" >
	<script src="js/jquery-3.1.1.js"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"></script>


    <style>

      table td{
		  text-align:center;
		  }
	  a:hover{
		  text-decoration:none;
		  }	  
	  .ins:hover{
		  color:red;
		  cursor:default;
		  }	  
    </style>

   <table class="table table-bordered table-hover"><tr><td></td><td>星期一</td><td>星期二</td><td>星期三</td><td>星期四</td><td>星期五</td></tr>
Eof;


$result = $con->query($sql);
$data = mysqli_fetch_assoc($result);



    if($data['Ctime']=='1-1') {

        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";

        echo "</table>";
    }elseif ($data['Ctime']=='2-1'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Ctime']=='3-1'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Ctime']=='4-1'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Ctime']=='5-1'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Ctime']=='1-2'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='2-2'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='3-2'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='4-2'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='5-2'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='1-3'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='2-3'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='3-3'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='4-3'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='5-3'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='1-4'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='2-4'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Ctime']=='3-4'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='4-4'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "</table>";
    }elseif ($data['Cname']=='5-4'){
        echo "<tr>";
        echo "<td class='ins'>一二节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>三四节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>五六节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "</tr>";
        echo "<tr>";
        echo "<td class='ins'>七八节</td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'></td>";
        echo "<td class='ins'>{$data['Cname']}</td>";
        echo "</tr>";
        echo "</table>";
    }

echo "<td><a href='pdf.php'>选课</a></td>";
?>